service: portfolio

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:NODE_ENV}
  region: us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV}

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-dotenv-plugin
  - serverless-apigw-binary
  # - serverless-domain-manager
  - serverless-offline

custom:
  apigwBinary:
    types:
      - '*/*'
  # customDomain:
  #   domainName: ${self:custom.secrets.DOMAIN}
  #   basePath: ''
  #   stage: ${self:custom.secrets.NODE_ENV}
  #   createRoute53Record: true
    ## endpointType: 'regional'
    ## if the ACM certificate is created in a region except for `'us-east-1'` you need `endpointType: 'regional'`
