service: portfolio

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:NODE_ENV}
  region: us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV}

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-dotenv-plugin
  - serverless-apigw-binary
  - serverless-domain-manager
  - serverless-offline

custom:
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${env:DOMAIN}
    certificateName: ${env:CERTIFICATE}
    basePath: ''
    stage: ${env:NODE_ENV}
    createRoute53Record: true
